#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34003
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("jp.nomula.pronama.lttimer.Resource", IsApplication=true)]

namespace jp.nomula.pronama.lttimer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int kei0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int kei1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int kei20 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int kei30 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int checkBox1 = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int checkBox2 = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int imageView1 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int imageView2 = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout2 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int numberPicker = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int pauseButton = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int startButton = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int textView2 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Sub = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int c0 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int c1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int c10 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int c2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int c3 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int c30 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int c4 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int c5 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int c6 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int c60 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int c7 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int c8 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int c9 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int end = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int start = 2130968590;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int app_info = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int back_confirm = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int cancel = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int duration_format = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int intent_duration = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int intent_soundon = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int lt_pause = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int lt_resume = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int lt_start = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int no = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int ok = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int setLTduration = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int voice_setting = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int web_site = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int yes = 2131034127;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
